### ISSUE TITLE
Pending of rendering photo

### ISSUE THREAD

**Issue by odinr** [equinor/fusion-web-components#811]
when photo of a person element is rendering there should be a placeholder (scrim/ghost/skeleton)

this should be added to the person avatar

**Comment by asbjornhaland** [comment]
Isn't there one already?
![image](https://github.com/equinor/fusion-web-components/assets/4287319/beeb2d14-f462-4e12-9e4c-0bfd4c1192e1)

**Comment by asbjornhaland** [comment]
@odinr will fix this in #895
