### ISSUE TITLE
Update storybook to V7

### ISSUE THREAD

**Issue by odinr** [equinor/fusion-web-components#895]
- [x] avatar
- [x] badge
- [x] button
- [x] icon button
- [x] link button
- [x] toggle button
- [x] chip
- [x] date range
- [x] date time
- [x] list
- [x] searchable dropdown
- [x] skeleton
- [x] checkbox
- [x] formfield
- [x] markdown-editor
- [x] markdown-viewer
- [x] menu
- [x] radio
- [x] select
- [x] switch
- [x] text area
- [x] text input
- [x] divider
- [x] progress indicator

__person elements__
- [x] avatar
- [x] card
- [x] list item
- [x] selector

**Comment by asbjornhaland** [comment]
All tasks are done, closing
