### ISSUE TITLE
Icon currentColor fill messing with searchable dropdown svg graphic

### ISSUE THREAD

**Issue by AndrejNikolicEq** [equinor/fusion-web-components#904]
**Is your feature request related to a problem? Please describe.**
Yes, the problem is that since icon element has `svg { fill: currentColor; }` in css, it fills up `<circle>` in custom icon with currentColor

![image](https://github.com/equinor/fusion-web-components/assets/101325152/d5277f57-dae8-4d45-a7dc-4e99c1b65a01)
![image](https://github.com/equinor/fusion-web-components/assets/101325152/e6ed4dbc-4435-4d21-8e19-941dbb46ac58)

**Describe the solution you'd like**
Remove fill for svg from css

**Comment by odinr** [comment]
will have a look at it

**Comment by asbjornhaland** [comment]
Please just set the fill to none:
```ts
          // Parse string to HTMLElement
          const parser = new DOMParser();
          const svgDoc = parser.parseFromString(appIcon ?? '', 'image/svg+xml');
          const svgElement = svgDoc.documentElement;

          // Add attribute
          svgElement.setAttribute('color', app.accentColor ?? app.category?.color ?? '#000');
          svgElement.style.fill = 'none';
          // ^-- Add this line

```
