### ISSUE TITLE
CSS variables for searchable dropdown result

### ISSUE THREAD

**Issue by AndrejNikolicEq** [equinor/fusion-web-components#905]
**Is your feature request related to a problem? Please describe.**
At some point, we will need to add css variables in searchable dropdown for:
- Icon/graphic size (both svg and eds)
- Top/bottom padding for single search result (currently over-ridden in web component)
- Search result list item height

**Comment by odinr** [comment]
can you provide an image to illustrate the issue

**Comment by odinr** [comment]
add part attribute to the fww-list item

**Comment by asbjornhaland** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/::part
